Repository GSG-FC02/Booklopedia-Project, pull requests merged in 2021-04, with the labels that each got.

#12 Create Read me file
  README.md
Labels: Done

#13 create all files for the app
  Book page/book.css
  Book page/book.html
  Book page/book.js
  Category page/category.css
  Category page/category.html
  Category page/category.js
  Mybooks page/mybooks.css
  Mybooks page/mybooks.html
  Mybooks page/mybooks.js
  Quotes page/quotes.css
  Quotes page/quotes.html
  Quotes page/quotes.js
  Search page/search.css
  Search page/search.html
  Search page/search.js
  Search2 page/search2.css
  Search2 page/search2.html
  Search2 page/search2.js
  home.css
  image/home logo.jpg
  image/mybooks.jpg
  index.html
Labels: Done

#14 Create the home page (Html file)
  home.css
  image/Component.png
  index.html
Labels: awaiting-review

#21 Quotes page 6
  Quotes page/quotes.css
  Quotes page/quotes.html
  Quotes page/quotes.js
Labels: Done

#19 Create html for book page
  Book page/book.css
  Book page/book.html
  Book page/book.js
Labels: awaiting-review

#20 Add the html file for the category page
  Category page/category.css
  Category page/category.html
  Category page/category.js
Labels: awaiting-review

#24 fix home button & pages links
  Book page/book.html
  Category page/category.html
  Category page/category.js
  Quotes page/quotes.css
  Quotes page/quotes.html
  Search page/search.html
  home.css
  index.html
Labels: approved

#22 Booksbage
  Mybooks page/books.png
  Mybooks page/mybooks.css
  Mybooks page/mybooks.html
  Mybooks page/mybooks.js
Labels: awaiting-review

#17 write html code for the My book page and Write css code for My books …
  .gitignore
  Mybooks page/mybooks.css
  Mybooks page/mybooks.html
Labels: in-progress

#26 edit general stylies
  Book page/book.css
  Book page/book.html
  Category page/category.css
  Category page/category.html
  Category page/category.js
  Mybooks page/mybooks.css
  Mybooks page/mybooks.html
  Mybooks page/mybooks.js
  Quotes page/quotes.css
  Quotes page/quotes.html
  Search page/search.css
  Search page/search.html
Labels: approved
